CREATE OR REPLACE TRIGGER zmiana_liczby_miejsc_wycieczki
 BEFORE UPDATE OF LICZBA_MIEJSC
 ON WYCIECZKI
 FOR EACH ROW
BEGIN
 SELECT :OLD.LICZBA_WOLNYCH_MIEJSC + :NEW.LICZBA_MIEJSC - :OLD.LICZBA_MIEJSC INTO
:NEW.LICZBA_WOLNYCH_MIEJSC FROM Dual;
end;
