CREATE OR REPLACE TYPE wycieczki_r as object (
 ID_WYCIECZKI NUMBER,
 NAZWA VARCHAR2(100),
 KRAJ VARCHAR2(50),
 "DATA" DATE,
 OPIS VARCHAR2(200),
 LICZBA_MIEJSC NUMBER,
 LICZBA_WOLNYCH_MIEJSC NUMBER
);
