CREATE VIEW wycieczki_miejsca
AS
SELECT
w.ID_WYCIECZKI,
w.NAZWA,
w.KRAJ,
w.DATA,
w.LICZBA_MIEJSC,
w.LICZBA_MIEJSC - (SELECT COUNT(*) FROM REZERWACJE r
where r.ID_WYCIECZKI = w.ID_WYCIECZKI and r.STATUS != 'A') AS WOLNE_MIEJSCA
FROM WYCIECZKI w;
